SELECT * FROM INFORMATION_SCHEMA.columns WHERE table_name
like 'student_depression'

--Academic pressure

SELECT academic_pressure , COUNT (*) FROM student_depression
GROUP BY academic_pressure
ORDER BY academic_pressure asc;

--study satisfaction
SELECT study_satisfaction , COUNT (*) FROM student_depression
GROUP BY study_satisfaction
ORDER BY study_satisfaction asc;


-- sleep duration
SELECT sleep_duration , COUNT (*) FROM student_depression
GROUP BY sleep_duration
ORDER BY sleep_duration desc;

--Dietary_Habits
SELECT dietary_habits , COUNT (*) FROM student_depression
GROUP BY dietary_habits
ORDER BY dietary_habits asc;

-- Having sucidal thoughts
SELECT "have_you_ever_had_suicidal_thoughts_?" , COUNT (*) FROM student_depression
GROUP BY "have_you_ever_had_suicidal_thoughts_?"
ORDER BY "have_you_ever_had_suicidal_thoughts_?" asc;

-- study_hours
SELECT study_hours , COUNT (*) FROM student_depression
GROUP BY study_hours
ORDER BY study_hours asc;

-- Financial stress
SELECT financial_stress , COUNT (*) FROM student_depression
GROUP BY financial_stress
ORDER BY financial_stress asc;

-- family history
SELECT family_history_of_mental_illness , COUNT (*) FROM student_depression
GROUP BY family_history_of_mental_illness
ORDER BY family_history_of_mental_illness asc;

--Depression

SELECT depression , COUNT (*) FROM student_depression
GROUP BY depression
ORDER BY depression asc;

 --Adding a index column


ALTER TABLE student_depression
ADD  COLUMN index_column INT GENERATED BY DEFAULT AS IDENTITY;


